# Generated by Django 3.0.8 on 2020-08-16 23:17

import client.models
from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=100, size=[241, 173], upload_to=client.models.client_image_upload_to),
        ),
    ]
