# Generated by Django 3.0.8 on 2020-08-15 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon_type',
            field=models.CharField(choices=[('أدوات', 'Tools'), ('شاكوش', 'Hammer'), ('صندوق أدوات', 'Toolbox'), ('مفك', 'ٍScrewdriver'), ('مفتاح', 'Wrench')], default=1, max_length=15),
            preserve_default=False,
        ),
    ]
