# Generated by Django 3.0.8 on 2020-08-16 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20200816_0203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icon_type',
            field=models.CharField(choices=[('tools', 'أدوات'), ('hammer', 'شاكوش'), ('toolbox', 'صندوق أدوات'), ('screwdriver', 'مفك'), ('wrench', 'مفتاح')], max_length=15),
        ),
    ]
